c=open('index.html','r',encoding='utf-8').read()
print('id=tokenModal:', c.find('id="tokenModal"'))
print('id=tokenSave:', c.find('id="tokenSave"'))
print('id=gearBtn:', c.find('id="gearBtn"'))
print('script count:', c.count('<script'))
print('tokenModal id line:', c[:c.find('id="tokenModal"')].count('\n')+1 if c.find('id="tokenModal"')>=0 else 'NOT FOUND')
print('tokenSave id line:', c[:c.find('id="tokenSave"')].count('\n')+1 if c.find('id="tokenSave"')>=0 else 'NOT FOUND')
print('gearBtn id line:', c[:c.find('id="gearBtn"')].count('\n')+1 if c.find('id="gearBtn"')>=0 else 'NOT FOUND')
print('last </script> line:', c[:c.rfind('</script>')].count('\n')+1)
print('file ends with:', repr(c[-50:]))
